[custom.all.idris2-go]
type        = "local"
path        = "."
ipkg        = "idris2-go.ipkg"
test        = "tests/compilertests.ipkg"
packagePath = true

[custom.all.idris2-go-lib]
type   = "local"
path   = "."
ipkg   = "idris2-go-lib.ipkg"
test   = "tests/libtests.ipkg"

