---
name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{ github.repository }} with Idris2 latest
    runs-on: ubuntu-latest
    env:
      PACK_DIR: /root/.pack
      GOFLAGS: "-buildvcs=false"
    strategy:
      fail-fast: false
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build lib
        run: pack build idris2-go-lib.ipkg
      - name: Build compiler
        run: pack --no-prompt build idris2-go.ipkg
      - name: Install runtime dependencies
        run: apt-get update && apt-get install --yes golang-go
      - name: Run lib test
        run: pack --no-prompt test idris2-go-lib
      - name: Run compiler test
        run: |
          pack --no-prompt install-app idris2-go
          pack --no-prompt test idris2-go

