---
name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{ github.repository }} with Idris2 latest
    runs-on: ubuntu-latest
    env:
      PACK_DIR: /root/.pack
      GOFLAGS: "-buildvcs=false"
    strategy:
      fail-fast: false
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build lib
        run: pack install idris2-go-lib
      - name: Build compiler
        run: pack --no-prompt install-app idris2-go
      - name: Run test
        run: |
          apt-get update && apt-get install --yes golang-go make
          pack install contrib test hedgehog
          IDRIS2=$PACK_DIR/bin/idris2-go make -C tests build
          IDRIS2=$PACK_DIR/bin/idris2-go make -C tests test INTERACTIVE=

